// Piece-set switching (chess variant only — excluded from the xiangqi sync).
//
// All piece artwork is base64-inlined into per-set CSS files generated by
// scripts/gen-piece-css.mjs (src/style/pieceSets/*.css), each scoped under
// the container class `.ct-pieceset-<key>`. Switching sets = swapping that
// class on the body element; chessground's bundled cburnett CSS remains as
// the fallback when no class matches (pieces never disappear).

import { Modal } from "obsidian";

import { t } from "./i18n";
import type ChessPlugin from "./main";
import type { ISettings } from "./types";
import { PIECE_SETS } from "./pieceSets.gen";

// Must match CLS_PREFIX in ./chess.ts and the generated CSS.
const CLS_PREFIX = "ct";
const PIECESET_CLASS_PREFIX = `${CLS_PREFIX}-pieceset-`;
const DEFAULT_PIECE_SET = "cburnett";

function pieceSetClass(key: string): string {
  return `${PIECESET_CLASS_PREFIX}${key}`;
}

/** Resolve a stored (possibly unknown/empty) piece-set key to a registry key. */
export function resolvePieceSetKey(key: string | undefined): string {
  return key && PIECE_SETS.some((s) => s.key === key) ? key : DEFAULT_PIECE_SET;
}

/** Swap the body-level `.ct-pieceset-*` container class. */
export function applyPieceSet(settings: ISettings): void {
  const key = resolvePieceSetKey(settings.pieceSet);
  const body = activeDocument.body;
  for (const cls of Array.from(body.classList)) {
    if (cls.startsWith(PIECESET_CLASS_PREFIX) && cls !== pieceSetClass(key)) {
      body.classList.remove(cls);
    }
  }
  body.classList.add(pieceSetClass(key));
}

/** Board-menu picker: a modal grid with a wN/bN thumbnail per set. */
function openPieceSetPicker(plugin: ChessPlugin): void {
  const modal = new Modal(plugin.app);
  modal.onOpen = () => {
    const { contentEl } = modal;
    contentEl.addClass(`${CLS_PREFIX}-piece-set-picker`);

    const title = contentEl.createDiv(`${CLS_PREFIX}-piece-set-picker__title`);
    title.setText(t("boardMenu.pieceSet"));

    const grid = contentEl.createDiv(`${CLS_PREFIX}-piece-set-picker__grid`);
    for (const set of PIECE_SETS) {
      const active =
        set.key === (plugin.settings.pieceSet || DEFAULT_PIECE_SET);
      const tile = grid.createEl("button", {
        cls: `${CLS_PREFIX}-piece-set-picker__tile${active ? ` ${CLS_PREFIX}-piece-set-picker__tile--active` : ""} ${pieceSetClass(set.key)}`,
      });
      const thumbs = tile.createDiv(`${CLS_PREFIX}-piece-set-picker__thumbs`);
      // Classes consumed by the generated per-set CSS.
      thumbs.createDiv(`${CLS_PREFIX}-piece-thumb wN`);
      thumbs.createDiv(`${CLS_PREFIX}-piece-thumb bN`);
      const label = tile.createDiv(`${CLS_PREFIX}-piece-set-picker__name`);
      label.setText(set.name);
      tile.addEventListener("click", () => {
        plugin.settings.pieceSet = set.key;
        void plugin.saveSettings();
        plugin.refresh();
        modal.close();
      });
    }
  };
  modal.onClose = () => {
    (modal as { contentEl: HTMLElement }).contentEl.empty();
  };
  modal.open();
}

/** Adapter capability consumed by the shared toolbar (null on xiangqi). */
export const PIECE_SET_PICKER = { open: openPieceSetPicker };

export { PIECE_SETS };
export type { PieceSetDef } from "./pieceSets.gen";
